// action action types
export const ACTION_STORAGE_LIST_LOAD_START = "ACTION_STORAGE_LIST_LOAD_START";
export const ACTION_STORAGE_LIST_LOAD_SUCCESS =
  "ACTION_STORAGE_LIST_LOAD_SUCCESS";
export const ACTION_STORAGE_LIST_LOAD_FAIL = "ACTION_STORAGE_LIST_LOAD_FAIL";

export const ACTION_REMOVE_START = "ACTION_REMOVE_START";
export const ACTION_REMOVE_SUCCESS = "ACTION_REMOVE_SUCCESS";
export const ACTION_REMOVE_FAIL = "ACTION_REMOVE_FAIL";

export const ACTION_STORE_START = "ACTION_STORE_START";
export const ACTION_STORE_SUCCESS = "ACTION_STORE_SUCCESS";
export const ACTION_STORE_FAIL = "ACTION_STORE_FAIL";

// auth action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// employee action types
export const EMPLOYEE_STORE_CLEAR = "EMPLOYEE_STORE_CLEAR";
export const EMPLOYEE_SET_EMPLOYEE = "EMPLOYEE_SET_EMPLOYEE";

export const EMPLOYEE_LIST_LOAD_START = "EMPLOYEE_LIST_LOAD_START";
export const EMPLOYEE_LIST_LOAD_SUCCESS = "EMPLOYEE_LIST_LOAD_SUCCESS";
export const EMPLOYEE_LIST_LOAD_FAIL = "EMPLOYEE_LIST_LOAD_FAIL";

export const EMPLOYEE_STORAGE_LIST_LOAD_START =
  "EMPLOYEE_STORAGE_LIST_LOAD_START";
export const EMPLOYEE_STORAGE_LIST_LOAD_SUCCESS =
  "EMPLOYEE_STORAGE_LIST_LOAD_SUCCESS";
export const EMPLOYEE_STORAGE_LIST_LOAD_FAIL =
  "EMPLOYEE_STORAGE_LIST_LOAD_FAIL";

export const EMPLOYEE_LOAD_START = "EMPLOYEE_LOAD_START";
export const EMPLOYEE_LOAD_SUCCESS = "EMPLOYEE_LOAD_SUCCESS";
export const EMPLOYEE_LOAD_FAIL = "EMPLOYEE_LOAD_FAIL";

export const EMPLOYEE_EDIT_START = "EMPLOYEE_EDIT_START";
export const EMPLOYEE_EDIT_SUCCESS = "EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAIL = "EMPLOYEE_EDIT_FAIL";

export const EMPLOYEE_CREATE_START = "EMPLOYEE_CREATE_START";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL = "EMPLOYEE_CREATE_FAIL";

export const EMPLOYEE_REMOVE_START = "EMPLOYEE_REMOVE_START";
export const EMPLOYEE_REMOVE_SUCCESS = "EMPLOYEE_REMOVE_SUCCESS";
export const EMPLOYEE_REMOVE_FAIL = "EMPLOYEE_REMOVE_FAIL";

// item action types
export const ITEM_STORAGE_LIST_LOAD_START = "ITEM_STORAGE_LIST_LOAD_START";
export const ITEM_STORAGE_LIST_LOAD_SUCCESS = "ITEM_STORAGE_LIST_LOAD_SUCCESS";
export const ITEM_STORAGE_LIST_LOAD_FAIL = "ITEM_STORAGE_LIST_LOAD_FAIL";

export const ITEM_STORAGE_EMPLOYEE_LIST_LOAD_START =
  "ITEM_STORAGE_EMPLOYEE_LIST_LOAD_START";
export const ITEM_STORAGE_EMPLOYEE_LIST_LOAD_SUCCESS =
  "ITEM_STORAGE_EMPLOYEE_LIST_LOAD_SUCCESS";
export const ITEM_STORAGE_EMPLOYEE_LIST_LOAD_FAIL =
  "ITEM_STORAGE_EMPLOYEE_LIST_LOAD_FAIL";

// product action types
export const PRODUCT_LIST_LOAD_START = "PRODUCT_LIST_LOAD_START";
export const PRODUCT_LIST_LOAD_SUCCESS = "PRODUCT_LIST_LOAD_SUCCESS";
export const PRODUCT_LIST_LOAD_FAIL = "PRODUCT_LIST_LOAD_FAIL";

// statistic action types
export const STATISTIC_STORAGE_LOAD_START = "STATISTIC_STORAGE_LOAD_START";
export const STATISTIC_STORAGE_LOAD_SUCCESS = "STATISTIC_STORAGE_LOAD_SUCCESS";
export const STATISTIC_STORAGE_LOAD_FAIL = "STATISTIC_STORAGE_LOAD_FAIL";

// storage action types
export const STORAGE_STORE_CLEAR = "STORAGE_STORE_CLEAR";
export const STORAGE_SET_STORE = "STORAGE_SET_STORE";

export const STORAGE_LIST_LOAD_START = "STORAGE_LIST_START";
export const STORAGE_LIST_LOAD_SUCCESS = "STORAGE_LIST_SUCCESS";
export const STORAGE_LIST_LOAD_FAIL = "STORAGE_LIST_FAIL";

export const STORAGE_LOAD_START = "STORAGE_LOAD_START";
export const STORAGE_LOAD_SUCCESS = "STORAGE_LOAD_SUCCESS";
export const STORAGE_LOAD_FAIL = "STORAGE_LOAD_FAIL";

export const STORAGE_EDIT_START = "STORAGE_EDIT_START";
export const STORAGE_EDIT_SUCCESS = "STORAGE_EDIT_SUCCESS";
export const STORAGE_EDIT_FAIL = "STORAGE_EDIT_FAIL";

// user action types
export const USER_LOAD_START = "USER_START";
export const USER_LOAD_SUCCESS = "USER_SUCCESS";
export const USER_LOAD_FAIL = "USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
