// action action types
export const ACTION_STORAGE_LIST_LOAD_START = "ACTION_STORAGE_LIST_LOAD_START";
export const ACTION_STORAGE_LIST_LOAD_SUCCESS = "ACTION_STORAGE_LIST_LOAD_SUCCESS";
export const ACTION_STORAGE_LIST_LOAD_FAIL = "ACTION_STORAGE_LIST_LOAD_FAIL";

// auth action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// employee action types
export const EMPLOYEE_STORAGE_LIST_LOAD_START = "EMPLOYEE_STORAGE_LIST_LOAD_START";
export const EMPLOYEE_STORAGE_LIST_LOAD_SUCCESS = "EMPLOYEE_STORAGE_LIST_LOAD_SUCCESS";
export const EMPLOYEE_STORAGE_LIST_LOAD_FAIL = "EMPLOYEE_STORAGE_LIST_LOAD_FAIL";

// item action types
export const ITEM_STORAGE_LIST_LOAD_START = "ITEM_STORAGE_LIST_LOAD_START";
export const ITEM_STORAGE_LIST_LOAD_SUCCESS = "ITEM_STORAGE_LIST_LOAD_SUCCESS";
export const ITEM_STORAGE_LIST_LOAD_FAIL = "ITEM_STORAGE_LIST_LOAD_FAIL";

// statistic action types
export const STATISTIC_STORAGE_LOAD_START = "STATISTIC_STORAGE_LOAD_START";
export const STATISTIC_STORAGE_LOAD_SUCCESS = "STATISTIC_STORAGE_LOAD_SUCCESS";
export const STATISTIC_STORAGE_LOAD_FAIL = "STATISTIC_STORAGE_LOAD_FAIL";

// storage action types
export const STORAGE_LIST_LOAD_START = "STORAGE_LIST_START";
export const STORAGE_LIST_LOAD_SUCCESS = "STORAGE_LIST_SUCCESS";
export const STORAGE_LIST_LOAD_FAIL = "STORAGE_LIST_FAIL";

export const STORAGE_LOAD_START = "STORAGE_LOAD_START";
export const STORAGE_LOAD_SUCCESS = "STORAGE_LOAD_SUCCESS";
export const STORAGE_LOAD_FAIL = "STORAGE_LOAD_FAIL";

export const STORAGE_EDIT_START = "STORAGE_EDIT_START";
export const STORAGE_EDIT_SUCCESS = "STORAGE_EDIT_SUCCESS";
export const STORAGE_EDIT_FAIL = "STORAGE_EDIT_FAIL";

// user action types
export const USER_LOAD_START = "USER_START";
export const USER_LOAD_SUCCESS = "USER_SUCCESS";
export const USER_LOAD_FAIL = "USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
