// action action types
export const ACTION_STORAGE_LIST_LOAD_START = "ACTION_STORAGE_LIST_LOAD_START";
export const ACTION_STORAGE_LIST_LOAD_SUCCESS =
  "ACTION_STORAGE_LIST_LOAD_SUCCESS";
export const ACTION_STORAGE_LIST_LOAD_FAIL = "ACTION_STORAGE_LIST_LOAD_FAIL";

export const ACTION_REMOVE_START = "ACTION_REMOVE_START";
export const ACTION_REMOVE_SUCCESS = "ACTION_REMOVE_SUCCESS";
export const ACTION_REMOVE_FAIL = "ACTION_REMOVE_FAIL";

export const ACTION_STORE_START = "ACTION_STORE_START";
export const ACTION_STORE_SUCCESS = "ACTION_STORE_SUCCESS";
export const ACTION_STORE_FAIL = "ACTION_STORE_FAIL";

// auth action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// employee action types
export const EMPLOYEE_STORE_CLEAR = "EMPLOYEE_STORE_CLEAR";

export const EMPLOYEE_LIST_LOAD_START = "EMPLOYEE_LIST_LOAD_START";
export const EMPLOYEE_LIST_LOAD_SUCCESS = "EMPLOYEE_LIST_LOAD_SUCCESS";
export const EMPLOYEE_LIST_LOAD_FAILURE = "EMPLOYEE_LIST_LOAD_FAILURE";

export const EMPLOYEE_SET_EMPLOYEE = "EMPLOYEE_SET_EMPLOYEE";
export const EMPLOYEE_LOAD_START = "EMPLOYEE_LOAD_START";
export const EMPLOYEE_LOAD_SUCCESS = "EMPLOYEE_LOAD_SUCCESS";
export const EMPLOYEE_LOAD_FAILURE = "EMPLOYEE_LOAD_FAILURE";

// item action types
export const ITEM_VIEW_LIST_LOAD_START = "ITEM_VIEW_LIST_LOAD_START";
export const ITEM_VIEW_LIST_LOAD_SUCCESS = "ITEM_VIEW_LIST_LOAD_SUCCESS";
export const ITEM_VIEW_LIST_LOAD_FAILURE = "ITEM_VIEW_LIST_LOAD_FAILURE";

export const ITEM_LIST_LOAD_START = "ITEM_LIST_LOAD_START";
export const ITEM_LIST_LOAD_SUCCESS = "ITEM_LIST_LOAD_SUCCESS";
export const ITEM_LIST_LOAD_FAILURE = "ITEM_LIST_LOAD_FAILURE";

// product action types
export const PRODUCT_LIST_LOAD_START = "PRODUCT_LIST_LOAD_START";
export const PRODUCT_LIST_LOAD_SUCCESS = "PRODUCT_LIST_LOAD_SUCCESS";
export const PRODUCT_LIST_LOAD_FAILURE = "PRODUCT_LIST_LOAD_FAILURE";

// statistic action types
export const STATISTIC_STORAGE_LOAD_START = "STATISTIC_STORAGE_LOAD_START";
export const STATISTIC_STORAGE_LOAD_SUCCESS = "STATISTIC_STORAGE_LOAD_SUCCESS";
export const STATISTIC_STORAGE_LOAD_FAILURE = "STATISTIC_STORAGE_LOAD_FAILURE";

// storage action types
export const STORAGE_STORE_CLEAR = "STORAGE_STORE_CLEAR";
export const STORAGE_SET_STORAGE = "STORAGE_SET_STORAGE";

export const STORAGE_LIST_LOAD_START = "STORAGE_LIST_START";
export const STORAGE_LIST_LOAD_SUCCESS = "STORAGE_LIST_SUCCESS";
export const STORAGE_LIST_LOAD_FAIL = "STORAGE_LIST_FAIL";

export const STORAGE_LOAD_START = "STORAGE_LOAD_START";
export const STORAGE_LOAD_SUCCESS = "STORAGE_LOAD_SUCCESS";
export const STORAGE_LOAD_FAIL = "STORAGE_LOAD_FAIL";

// user action types
export const USER_LOAD_START = "USER_START";
export const USER_LOAD_SUCCESS = "USER_SUCCESS";
export const USER_LOAD_FAIL = "USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
